# -*- coding: utf-8 -*-
"""Bulking

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPM3PoVsIRwkU4dakulTWtPJvztaQ5m8
"""

!pip install -q streamlit
!npm install -q localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import os
# from datetime import date
# 
# DATA_FILE = "mission_60kg_data.csv"
# 
# def load_data():
#     if os.path.exists(DATA_FILE):
#         return pd.read_csv(DATA_FILE)
#     else:
#         columns = ["Date", "Weight", "Eggs", "Sattu", "Soya", "Banana", "Potatoes", "Workout_Type"]
#         return pd.DataFrame(columns=columns)
# 
# def save_data(new_row):
#     df = load_data()
#     df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
#     df.to_csv(DATA_FILE, index=False)
# 
# st.set_page_config(page_title="Mission 60KG Tracker", page_icon="💪", layout="centered")
# 
# st.title("🚀 Mission 60KG Tracker")
# st.markdown("Track your ₹1000/month hostel diet and 5:30 AM workouts.")
# 
# tab1, tab2 = st.tabs(["📝 Daily Log", "📊 My Progress"])
# 
# with tab1:
#     st.header("Log Today's Progress")
#     col1, col2 = st.columns(2)
#     with col1:
#         log_date = st.date_input("Date", date.today())
#     with col2:
#         weight = st.number_input("Current Weight (kg)", min_value=40.0, max_value=80.0, value=50.0, step=0.1)
# 
#     st.subheader("🟢 Daily Diet Non-Negotiables")
#     ate_eggs = st.checkbox("2 Boiled Eggs 🥚")
#     ate_sattu = st.checkbox("Heavy Sattu Drink 🥤")
#     ate_soya = st.checkbox("30g Soya Chunks 🍲")
#     ate_banana = st.checkbox("1 Banana 🍌")
#     ate_potatoes = st.checkbox("2 Boiled Potatoes 🥔")
# 
#     st.subheader("💪 Workout Log")
#     workout_type = st.selectbox("What did you train today at 5:30 AM?",
#                                 ["Rest Day", "Push (Chest/Triceps/Shoulders)", "Legs & Core", "Pull (Back/Biceps)", "Full Body Density"])
# 
#     if st.button("💾 Save Daily Log"):
#         new_entry = {
#             "Date": str(log_date),
#             "Weight": weight,
#             "Eggs": ate_eggs,
#             "Sattu": ate_sattu,
#             "Soya": ate_soya,
#             "Banana": ate_banana,
#             "Potatoes": ate_potatoes,
#             "Workout_Type": workout_type
#         }
#         save_data(new_entry)
#         st.success("Log saved successfully! Keep pushing for that 60kg.")
# 
# with tab2:
#     st.header("📈 Weight Gain Dashboard")
#     df = load_data()
#     if not df.empty:
#         st.subheader("Weight Trend")
#         df_chart = df.sort_values(by="Date")
#         st.line_chart(df_chart.set_index("Date")["Weight"])
#         st.subheader("Raw Data Log")
#         st.dataframe(df)
#     else:
#         st.info("No data yet. Save your first log in the 'Daily Log' tab!")

import urllib
print("👉 Password/Endpoint IP:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))
print("1. Copy the IP address above.")
print("2. Click the localtunnel url below (it ends in .loca.lt).")
print("3. Paste the IP address into the 'Endpoint IP' box on that webpage and click Submit.")

!streamlit run app.py & npx localtunnel --port 8501